config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get '/reviews',         to: 'static_pages#reviews'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'messages#new', as: 'new_message'
  post '/contact',        to: 'messages#create', as: 'create_message'
  get '/purchase',        to: 'static_pages#purchase'
  
  get '/whateverman',    to: 'static_pages#secret'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    include ActiveModel::Model
    attr_accessor :name, :email, :content
    validates :content, presence: true
    validates :name,  presence: true, length: { maximum: 50 }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 245 },
                      format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :detect_device_variant
  
  private
    
  def detect_device_variant
    request.variant = :phone if browser.device.mobile?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def new
        @message = Message.new
    end
    
    def create
    @message = Message.new message_params

        if @message.valid?
            ContactMailer.contact_me(@message).deliver_now
            flash[:info] = "Thank you for your message!" 
            redirect_to root_path 
        else
            render :new
        end
    end

  private

  def message_params
    params.require(:message).permit(:name, :email, :content)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    
   
    def secret
         videoArray = ["src=https://www.youtube.com/embed/QlDnQHI0c-4",
                       "src=https://www.youtube.com/embed/453wgsWT5Ao",
                       "src=https://www.youtube.com/embed/hShYnVEmbb4",
                       "src=https://www.youtube.com/embed/lHbAsndSKXA",
                       "src=https://www.youtube.com/embed/ooWrm3Lo7rs",
                       "src=https://www.youtube.com/embed/OEfOkcmXEyQ",
                       "src=https://www.youtube.com/embed/Dq4-nAaYbXA",
                       "src=https://www.youtube.com/embed/tnhEdBG1fDI",
                       "src=https://www.youtube.com/embed/M2E1m90YSpA",
                       "src=https://www.youtube.com/embed/LEhHRvwSBxE",
                       "src=https://www.youtube.com/embed/k4pKFaF41mk",
                       "src=https://www.youtube.com/embed/9C_HReR_McQ",
                       "src=https://www.youtube.com/embed/G9FGgwCQ22w",
                       "src=https://www.youtube.com/embed/KaqC5FnvAEc",
                       "src=https://www.youtube.com/embed/4B-wFx0aMlw",
                       "src=https://www.youtube.com/embed/lHxFjYikeBU"]
         
         
         @videSelection = videoArray.sample(1).map(&:inspect).join(", ").to_s
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns title of page
    def full_title(page_title = '')
        base_title = "Whatever Man"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_application_layout.html.erb
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <% #debug(params) if Rails.env.development? %>
    </div>

app/views/layouts/_buttons.html.erb
<div class="row social-buttons">

<div class="col-sm-2">
<style>.ig-b- { display: inline-block; }
.ig-b- img { visibility: hidden; }
.ig-b-:hover { background-position: 0 -60px; } .ig-b-:active { background-position: 0 -120px; }
.ig-b-32 { width: 32px; height: 32px; background: url(//badges.instagram.com/static/images/ig-badge-sprite-32.png) no-repeat 0 0; }
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
.ig-b-32 { background-image: url(//badges.instagram.com/static/images/ig-badge-sprite-32@2x.png); background-size: 60px 178px; } }</style>
<a href="https://www.instagram.com/whatevermanthegame/?ref=badge" class="ig-b- ig-b-32"><img src="//badges.instagram.com/static/images/ig-badge-32.png" alt="Instagram" /></a>
</div>

<div class="col-sm-2">
<div class="fb-like" data-href="https://www.facebook.com/Whatever-Man-The-Game-376688969458003/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
</div>

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
    <div clas="container">
        <div class="center">
            <h1>Whatever Man</h1>
        </div>
    </div>
</div>

app/views/layouts/_menu.html.erb
<div class="menu-header" onclick="openNav()">Menu</div>

<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <%= link_to "Create Your Profile", new_message_path, id: "logo-four-phone" %>
      <%= link_to "Services", services_path, id: "logo-four-phone" %>
      <%= link_to "Pricing & About", about_path, id: "logo-four-phone" %>
</div>

<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.body.style.backgroundColor = "white";
}
</script>

app/views/layouts/_paypal_button.html.erb
<div class="paypalbutton">
	<div class="center">
		
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="HY5L37PPXUUAY">
<table>
<tr><td><input type="hidden" name="on0" value="Options"><b>How many do you want?</b></td></tr><tr><td><select name="os0">
	<option value="1 Game">1 Game $0.01 USD</option>
	<option value="2 Games">2 Games $0.02 USD</option>
	<option value="3 Games">3 Games $0.03 USD</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="0" height="0">
</form>

	</div>
</div>

app/views/layouts/_paypal_button_phone.html.erb
<div class="paypalbutton-phone">
	<div class="center">
		
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="HY5L37PPXUUAY">
<table>
<tr><td><input type="hidden" name="on0" value="Options"><b>How many do you want?</b></td></tr><tr><td><select name="os0">
	<option value="1 Game">1 Game $0.01 USD</option>
	<option value="2 Games">2 Games $0.02 USD</option>
	<option value="3 Games">3 Games $0.03 USD</option>
</select> </td></tr>
</table>
<input type="hidden" name="currency_code" value="USD">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="0" height="0">
</form>

	</div>
</div>

app/views/layouts/_phone_header.html.erb
<header class="navbar navbar-default navbar-static-top">
    <div class="container">
            <%= render 'layouts/menu' %>
    </div>
    <br>
    <div class="container-center">
        <%= link_to "Social Curation", root_path, method: :get, id: "logo" %>
    </body>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/_sidebar-right.html.erb
<div class="sidebar-right">
    
</div>

app/views/layouts/application.html+phone.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:url"           content="http://whatever-man-board-game-christianorourke.c9users.io:8080/" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Whatever Man the Game" />
  <meta property="og:description"   content="Whatever Man the game, by Emily Hill" />
  <meta property="og:image"         content="assets/diamond.jpg" />

<%= render 'shared/preloader' %>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
      
      <nav class="navbar navbar-fixed-top">
       <%= image_tag 'header.png', style: 'width:100%;' %>
      </nav>

  </head>
  
  <body id="phone-body">
  
    <%= render 'layouts/sidebar-left' %>
    <%= render 'layouts/sidebar-right' %>      
    
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12';
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>



        
    <div id="skrollr-body">
  
        <%= render 'layouts/application_layout' %>
        
     
        <%= yield %>
        
	  </div>
	  
	  <script type="text/javascript">
      $(function(){
        skrollr.init({forceHeight: false});
      });
    </script>
    
  </body>
	<nav class="navber navbar-fixed-bottom"><%= image_tag 'footer.png', style: 'width:100%;' %></nav>
</html>

<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <meta property="og:url"           content="http://whatever-man-board-game-christianorourke.c9users.io:8080/" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="Whatever Man the Game" />
  <meta property="og:description"   content="Whatever Man the game, by Emily Hill" />
  <meta property="og:image"         content="assets/diamond.jpg" />
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
  </head>
  
  <body>
    
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.12';
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    </script>


    <div id="skrollr-body">
        
        <%= render 'layouts/application_layout' %>
        <%= render 'layouts/sidebar-left' %>
        <%= render 'layouts/sidebar-right' %>
     
        <%= yield %>
        
	  </div>
	  
	  <script type="text/javascript">
      $(function(){
        skrollr.init({forceHeight: false});
      });
    </script>
    
  </body>
	<nav class="navber navbar-fixed-bottom"><%= image_tag 'footer.png', style: 'width:100%;' %></nav>
</html>

<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="skrollr-body">
        
        <%= render 'layouts/application_layout' %>
        <%= render 'layouts/sidebar-left' %>
        <%= render 'layouts/sidebar-right' %>
     
        <%= yield %>
    
    <script type="text/javascript">
	    skrollr.init({
		    forceHeight: false;
		    smoothScrolling: true
	    });
	  </script>
	  </div>
  </body>
  
  <footer>
    <br />
    <br />
    <br />
    <br />
    <p>© Whatever Man 2018  | Game and graphic design by Emily Hill 2018</p>
  </footer>
</html>

<link href="https://fonts.googleapis.com/css?family=Berkshire+Swash" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">

app/views/messages/new.html+phone.erb
<% provide(:title, "Contact") %>
<div class="center">
    <div class="cloud-container-phone">
          <div class="vertc-phone">
            
            <div class="phone-logo">Contact Us!</div>
            
          </div>
        </div>
        
<div class="cloud-container-phone">
  <div class="vertc-phone">
    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
  </div>
</div>

</div>

app/views/messages/new.html.erb
 <%= render 'shared/preloader' %>

<nav class="navbar navbar-fixed-top">
   <%= image_tag 'header.png', style: 'width:100%;' %>
 </nav> 


<div id="main-bcg">
  <div class="bcg">
  
  <div class="row">
    <div class="col-md-6 col-centered">
    
    <div style="padding-left:60px;">
      <div class="cloud-container">
        <div class="vertc">
              
          <h1>Contact Us!</h1>
          
        </div>
      </div>
    </div>
    
      <div class="padding-desktop"></div>  
      
<% @message = Message.new %>

    <%= form_for @message, url: create_message_url do |f| %>
      <%= notice %>
      <%= @message.errors.full_messages.join(', ') %>

      <%= f.text_field :name, placeholder: 'name' %>
      <%= f.email_field :email, placeholder: 'email' %>
      <%= f.text_area :content, placeholder: 'message' %>
      <%= f.submit 'Send' %>
    <% end %>
 
&nbsp;
      
  <div class="padding-desktop"></div>
  
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_preloader.html+phone.erb
<div class="preloader"><span class="preloader-gif-phone"></span></div>

app/views/shared/_preloader.html.erb
<div class="preloader"><span class="preloader-gif"></span></div>

app/views/static_pages/about.html+phone.erb
<div class="center">

<div class="phone-pad"></div>

        <div class="cloud-container-phone">
          <div class="vertc-phone">
            
            <div class="phone-logo">About</div>
            
          </div>
        </div>

<div class="phone-pad"></div>
<div class="phone-pad"></div>

        <div data-0="padding-left:-50px" data-1400="padding-left:-150px;" data-1900='padding-left:-50px;'>
        
        <div class="cloud-container-phone">
          <div class="vertc-phone">
                <div class="phone-text">
                  Heres what the game is about: kusdgbvlzsbfwbfWBFLiueabifuhae Test shdbfvaehgfblIFBlFBlIBF TEST SKJDfbGFIUGqwifbksdjvbksjzdlhgfkzjhfgafguLY
                </div>
              </div>
            </div>
            
          </div>
          
<div class="phone-pad"></div>
<div class="phone-pad"></div>

      <ul>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Home', root_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Customers', reviews_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Buy', purchase_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Contact Us!', new_message_path, method: :get %></h1></button></li>
      </ul>
      
<div class="phone-pad"></div>

</div>

app/views/static_pages/about.html.erb
 <%= render 'shared/preloader' %>

<head>
 <nav class="navbar navbar-fixed-top">
   <%= image_tag 'header.png', style: 'width:100%;' %>
 </nav> 
</head>

<div id="main-bcg">
    <div class="bcg">
    
    
    
        <div class="col-lg-6 col-centered">
            
            &nbsp;
            <%= render 'layouts/buttons' %>
        </div>  
        
    
    
    </div>
    
</div>
</div>

app/views/static_pages/home.html+phone.erb
<% provide(:title, "home") %>
  
<div class="center">

<div class="phone-pad"></div>

<%= image_tag 'logo-cloud', class: 'cloud-phone', style: 'position:relative; z-index:1040;' %>

        <div class="cloud-container-phone">
          <div class="vertc-phone">
            <ul>
            <li><div class="phone-logo">Whatever Man</div></li>
            </ul>
          </div>
        </div>

<div class="phone-pad"></div>
<div class="phone-pad"></div>
      
      
      <ul>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'About', about_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Customers', reviews_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Buy', purchase_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Contact Us!', new_message_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Whatever Man', whateverman_path, method: :get %></h1></button></li>
      </ul>
      
      <%= render 'layouts/buttons' %>
      
    </div>
    
<div class="phone-pad"></div>
    



    

app/views/static_pages/home.html.erb
<%= render 'shared/preloader' %>

 <nav class="navbar navbar-fixed-top">
   <%= image_tag 'header.png', style: 'width:100%;' %>
 </nav> 


<div id="main-bcg">
  <div class="bcg">
    
    <div class="padding-main">
      
    <div class="center">
      <%= image_tag 'logo-cloud', style: 'position:relative; z-index:1040;' %>
      &nbsp;
      
      <ul>
        <li><button class="btn btn-primary btn-lg logo"><h1><%= link_to 'About', about_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-lg"><h1><%= link_to 'Customers', reviews_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-lg"><h1><%= link_to 'Buy', purchase_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-lg"><h1><%= link_to 'Contact Us!', new_message_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-lg"><h1><%= link_to 'Whatever Man', whateverman_path, method: :get %></h1></button></li>
      </ul>
      
      <%= render 'layouts/buttons' %>
      
    </div>
    
    </div>
    
</div>
</div>

app/views/static_pages/purchase.html+phone.erb
<% provide(:title, "Buy the Game!") %>
    
<div class="center">

<div class="phone-pad"></div>

        <div class="cloud-container-phone">
          <div class="vertc-phone">
            <ul>
            <li><div class="phone-logo">Get your own man!</div></li>
            </ul>
          </div>
        </div>

<div class="phone-pad"></div>
<div class="phone-pad"></div>
      
<%= image_tag 'whatever-bcg-old.jpg', class: 'buy-image' %>
&nbsp;
<%= render 'layouts/paypal_button_phone' %>
      
<div class="phone-pad"></div>
<div class="phone-pad"></div>

      <ul>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Home', root_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'About', about_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Customers', reviews_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Contact Us!', new_message_path, method: :get %></h1></button></li>
      </ul>
      
      <%= render 'layouts/buttons' %>
      

    
<div class="phone-pad"></div>
</div>    



    

app/views/static_pages/purchase.html.erb
 <%= render 'shared/preloader' %>

<head>
 <nav class="navbar navbar-fixed-top">
   <%= image_tag 'header.png', style: 'width:100%;' %>
 </nav> 
</head>

<div id="main-bcg">
    <div class="bcg">
      <div class="center">
        <%= image_tag 'logo-cloud', style: 'position:relative; z-index:1040;' %>
      </div>
      
      <div id="slide-menu">
          <div class="bcg">
            <h1><span>
              Get your own bro!
            </span></h1>
          </div>
      </div>

    </div>
</div>


<div id="main-bcg">
    <div class="bcg">        


<div class="bottom-padding" style="padding-top: 25px;">
        <div class="container-fluid">
            
            <div class="center">
                <%= image_tag 'whatever-bcg-old.jpg', class: 'buy-image' %>
                &nbsp;
                <%= render 'layouts/paypal_button' %>
            </div>
            
        </div>
</div>
        
        
    </div>
</div>

app/views/static_pages/reviews.html+phone.erb
<div class="center">

<div class="phone-pad"></div>

        <div class="cloud-container-phone">
          <div class="vertc-phone">
            
            <div class="phone-logo">Reviews!</div>
            
          </div>
        </div>

<div class="phone-pad"></div>
<div class="phone-pad"></div>

        <div data-0="padding-left:50px" data-1400="padding-left:150px;" data-1900='padding-left:50px;'>
        
        <div class="cloud-container-phone">
          <div class="vertc-phone">
                <%= image_tag '10guy-1', style: 'max-height:200px; max-width:200px; z-index:999;'%>
              </div>
            </div>
            
          </div>
       
          <div data-0="padding-left:150px" data-1800="padding-left:60px;" data-2300='padding-left:150px;'>
          <div class="cloud-container-phone">
            <div class="vertc-phone">
              
                <div class="phone-text">dat review boi</div>
              
              </div>
            </div>
            </div>

<div class="phone-pad"></div>


        <div data-0="padding-left:50px" data-2500="padding-left:150px;" data-3000='padding-left:50px;'>
        
        <div class="cloud-container-phone">
          <div class="vertc-phone">
                <%= image_tag '10guy-2', style: 'max-height:200px; max-width:200px; z-index:999;'%>
              </div>
            </div>
            
          </div>
       
          <div data-0="padding-left:150px" data-2900="padding-left:60px;" data-3500='padding-left:150px;'>
          <div class="cloud-container-phone">
            <div class="vertc-phone">
              
                 <div class="phone-text">another review</div>
              
              </div>
            </div>
            </div>

<div class="phone-pad"></div>


        <div data-0="padding-left:50px" data-3600="padding-left:150px;" data-4000='padding-left:50px;'>
        
        <div class="cloud-container-phone">
          <div class="vertc-phone">
                <%= image_tag '10guy-3', style: 'max-height:200px; max-width:200px; z-index:999;'%>
              </div>
            </div>
            
          </div>
       
          <div data-0="padding-left:150px" data-3900="padding-left:60px;" data-4700='padding-left:150px;'>
          <div class="cloud-container-phone">
            <div class="vertc-phone">
              
                 <div class="phone-text">2hi4Areview</div>
              
              </div>
            </div>
            </div>

<div class="phone-pad"></div>
<div class="phone-pad"></div>

      <ul>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Home', root_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'About', about_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Buy', purchase_path, method: :get %></h1></button></li>
        <li><button class="btn btn-primary btn-xlarge"><h1><%= link_to 'Contact Us!', new_message_path, method: :get %></h1></button></li>
      </ul>
      
<div class="phone-pad"></div>


</div>

app/views/static_pages/secret.html+phone.erb
<%= render 'shared/preloader' %>

<head>
 <nav class="navbar navbar-fixed-top">
   <%= image_tag 'header.png', style: 'width:100%;' %>
 </nav> 
</head>


    
    
    
    <div class="youtube-responsive-container">
        '<iframe width="560" height="315" <%= @videSelection.chomp('"').reverse.chomp('"').reverse %>?rel=0&amp;autoplay=1&amp;controls=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>'
    </div>
    
    
    

app/views/static_pages/secret.html.erb
<%= render 'shared/preloader' %>

<head>
 <nav class="navbar navbar-fixed-top">
   <%= image_tag 'header.png', style: 'width:100%;' %>
 </nav> 
</head>

<div id="main-bcg">
    <div class="bcg">
    
    
    <div class="video-background">
    <div class="video-foreground">
       '<iframe width="560" height="315" <%= @videSelection.chomp('"').reverse.chomp('"').reverse %>?rel=0&amp;autoplay=1&amp;controls=0&amp;showinfo=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>' 
       
       
    </div>
    </div>
        
    
    
    </div>
    
</div>
</div>